# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:

services:
    user_service:
        class: NewBundle\Service\UserService
        arguments: 
            - "@doctrine.orm.default_entity_manager"
            - "@translator"
            # - "@service_container" 
            # - '@doctrine.orm.entity_manager' 

    task_service:
        class: NewBundle\Service\TaskService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@translator"